### PR TITLE
added top10 component

### PR DESCRIPTION
**Pull request by muruga21**
Hello @bishwobista ,

I have successfully created a new component, which marks my first open-source contribution. Thank you for this opportunity. I have a question: should I create an empty component only? Please let me know, as I am eager to contribute to your project.

### CODE REVIEW

**Comment by bishwobista** [comment]
You changed "Navbar" to "Navbar." idk why. And deleted the original Navbar?

**Comment by muruga21** [comment]
The old import statement was like this..

import Navbar from "./components/Navbar./Navbar"; 

this shows an error that Navbar. does'nt exists.

so i changed ' Navbar. '  to 'Navbar'

**Comment by muruga21** [comment]
image


please check this

**Comment by bishwobista** [comment]
Yea, the Navbar must have been mistakenly deleted. Right now, I cannot merge. You can remove the project and clone again and edit and send another pull request.

**Pull request closed without merging**
